<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

### Exercise 1

| # |    Term    | Brief Description                                                                                    |
|:-:|:----------:|------------------------------------------------------------------------------------------------------|
| 1 | Subsetting | Subsetting means to generally select data from a list or an array                                    |
| 2 | Indexing   | Indexing means selecting one element from a list or an array based on their position in the data set |
| 3 | Slicing    | To select a range of elements                                                                        |
| 4 | Masking    | A form of subsetting. _Only works with NumPy arrays._                                                |

### Exercise 2

In [98]:
import numpy as np

In [100]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

In [102]:
np_array_2d[:,0].astype(int)

array([ 1,  3,  2,  4,  5,  7,  6,  8, 10,  9])

In [104]:
np_array2d1 = np_array_2d[:,0].astype(int)

In [106]:
np_array2d1 % 2

array([1, 1, 0, 0, 1, 1, 0, 0, 0, 1], dtype=int32)

In [108]:
np_array2d1 % 2 == 1

array([ True,  True, False, False,  True,  True, False, False, False,
        True])

In [110]:
my_mask = (np_array2d1 % 2 == 1) == True

In [114]:
np_array_2d[my_mask,1]

array(['A', 'C', 'E', 'G', 'I'], dtype='<U11')

### Exercise 3

In [161]:
py_list = [[66, 50, 57, -1, -1],
           [92, -1, 88, -1, -1],
           [75, -1, -1, 76, -1],
           [-1, 51, 87, -1, -1],
           [71, -1, 67, -1, 69]]

In [163]:
np_array = np.array(py_list)

In [165]:
my_mask_1 = np_array < 50
my_mask_2 = np_array > 50
my_mask_3 = np_array == 50

In [167]:
np_array[my_mask_1] = -1
np_array[my_mask_2] = 1
np_array[my_mask_3] = 0

In [170]:
print(np_array)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
