<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

In [7]:
import numpy as np

In [ ]:
list = [1,2,3,4,5] # Never use list as a variable. It is a python keywor (e.g. print, for list)

In [3]:
py_list=[1,2,3,4,5]

In [13]:
py_list # used to grow data

[1, 2, 3, 4, 5]

In [9]:
np_array = np.array([1,2,3,4,5])

In [11]:
np_array # used for mathematcial scientific stuff

array([1, 2, 3, 4, 5])

In [15]:
np_array = np.array(py_list)

In [17]:
np_array

array([1, 2, 3, 4, 5])

### Things you can do or not

In [28]:
py_list = [1,2,3,4,5]
np_array = np.array([1,2,3,4,5])

In [30]:
py_list + 1

TypeError: can only concatenate list (not "int") to list

In [36]:
py_list + [1]

[1, 2, 3, 4, 5, 1]

In [34]:
np_array +1

array([2, 3, 4, 5, 6])

In [38]:
py_list*2 # List works with the whole list

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [40]:
np_array*2 # Numpy works with each of the elements. Numpy useful for mathematical stuff

array([ 2,  4,  6,  8, 10])

In [42]:
len(py_list) # Tells you how big your list is

5

In [44]:
len (np_array)

5

In [48]:
np_array.size

5

In [50]:
np_array.shape

(5,)

In [52]:
'a' in ['a','b','c']

True

In [54]:
my_rand_numbers=np.random.randint(0,100,10)

In [58]:
my_rand_numbers

array([28, 46, 83, 67, 70, 83, 13, 92,  4, 17])

In [60]:
my_rand_numbers < 50

array([ True,  True, False, False, False, False,  True, False,  True,
        True])

In [62]:
mask = my_rand_numbers < 50

In [64]:
my_rand_numbers[mask]

array([28, 46, 13,  4, 17])

In [70]:
mask = (my_rand_numbers < 50) & (my_rand_numbers%2==0) # & can be used to combine condition. | means or. MASKING

In [68]:
my_rand_numbers[mask]

array([28, 46,  4])

In [72]:
10/3

3.3333333333333335

In [74]:
10//3

3

In [76]:
10%3

1

In [78]:
my_rand_numbers

array([28, 46, 83, 67, 70, 83, 13, 92,  4, 17])

In [84]:
my_rand_numbers[0] # Python is 0 index. So first position is 0.
                    # [] is indexing to extract a subset of the values. 

28

In [86]:
my_rand_numbers[-1] # Applies to lists as well as arrays

17

In [88]:
py_2d_list = [[1,2,3],[4,5,6],[7,8,9]] # 2d list meaning that the list contains other lists

In [90]:
py_2d_list[0]

[1, 2, 3]

In [92]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

In [94]:
py_list_2d

[[1, 'A'],
 [2, 'B'],
 [3, 'C'],
 [4, 'D'],
 [5, 'E'],
 [6, 'F'],
 [7, 'G'],
 [8, 'H'],
 [9, 'I'],
 [10, 'J']]

In [96]:
np_array_2d # Numpy arrays dont tolerate different types (e.g. numbers, strings)

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C'],
       ['4', 'D'],
       ['5', 'E'],
       ['6', 'F'],
       ['7', 'G'],
       ['8', 'H'],
       ['9', 'I'],
       ['10', 'J']], dtype='<U11')

In [98]:
py_list_2d[0]

[1, 'A']

In [100]:
py_list_2d[0][1]

'A'

In [102]:
np_array_2d[0,1]

'A'

In [ ]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

# Dictionary has a key and a value

In [108]:
superhero_info = {
    "Natasha Romanoff": ["Black Widow", "Joannsson"],
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

In [110]:
superhero_info['Natasha Romanoff']

['Black Widow', 'Joannsson']

# What to expect in this chapter

# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

## 1.2 Accessing data from a list (or array)

## 1.3 Accessing data from a dictionary

## 1.4 Higher dimensional lists

# 2 Lists vs. Arrays

## 2.1 Size

## 2.2 Arrays are fussy about type

## 2.3 Adding a number

## 2.4 Adding another list

## 2.5 Multiplying by a Number

## 2.6 Squaring

## 2.7 Asking questions

## 2.8 Mathematics

## Footnotes