<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

In [4]:
import numpy as np

In [6]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one
x = py_list  # OR
x = np_array

In [8]:
py_list[3:6] # Stops one less. (i.e. gives you 3 elements)

['d4', 'e5', 'f6']

In [10]:
py_list[0:6:2] # Tries to give 6 elements but in steps of 2]

['a1', 'c3', 'e5']

In [12]:
py_list[-1::-1] # Starts at the end, goes to the start, in steps of -1

['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1']

In [22]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

In [24]:
py_list_2d[1:4]

[[2, 'B'], [3, 'C'], [4, 'D']]

In [26]:
np_array_2d[1:4]

array([['2', 'B'],
       ['3', 'C'],
       ['4', 'D']], dtype='<U11')

In [30]:
np_array_2d[1:4,1]

array(['B', 'C', 'D'], dtype='<U11')

In [36]:
np_array_2d[:,0].astype(int) # To upgrade to int so that math can be done

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
np_array_2d[:,0].astype(int)**3

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

### Growing to List

In [43]:
[1,2] + [8,9,0] + ['A', 'B']

[1, 2, 8, 9, 0, 'A', 'B']

In [51]:
np.array([1,2,3]) + np.array([8,9,0]) # Numpy array tries to do element wise operations (i.e. adds individul elemetns)

array([ 9, 11,  3])

In [53]:
x=[1]
x= x + [2]
x= x + [3]
x= x + [4]
x

[1, 2, 3, 4]

In [55]:
x=[1]
x+= [2]
x+= [3]
x+= [4]
x

[1, 2, 3, 4]

In [59]:
x=[1]
x.append(2)
x.append(3)
x.append(4)
x

# Append runs about 1.5 times faster than the rest

[1, 2, 3, 4]

In [61]:
x=[1,2,3]

In [63]:
x[0]=1000

In [65]:
x

[1000, 2, 3]

In [81]:
y=(1,2,3) # Define Tupple. Tuples are similar to lists, except they use ( ) and cannot be changed after creation (i.e., they are immutable).

In [78]:
y[0]=1000

TypeError: 'tuple' object does not support item assignment

In [89]:
x=[1, 2, 3]
y=x           # DON'T do this!
z=x           # DON'T do this!
print(f'Before: {x=}, {y=}, {z=}')
x[0]=10000
print(f'After: {x=}, {y=}, {z=}')
# Design feature of python

Before: x=[1, 2, 3], y=[1, 2, 3], z=[1, 2, 3]
After: x=[10000, 2, 3], y=[10000, 2, 3], z=[10000, 2, 3]


In [93]:
x=[1, 2, 3]
y=x.copy()           # do this!
z=x.copy()           # do this!
print(f'Before: {x=}, {y=}, {z=}')
x[0]=10000
print(f'After: {x=}, {y=}, {z=}')


Before: x=[1, 2, 3], y=[1, 2, 3], z=[1, 2, 3]
After: x=[10000, 2, 3], y=[1, 2, 3], z=[1, 2, 3]


# What to expect in this chapter

# 1 Subsetting: Indexing and Slicing

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

## 1.2 Arrays only | Subsetting by masking

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

## 1.4 Growing lists

# Some loose ends

## 1.5 Tuples

## 1.6 Be VERY careful when copying

## Footnotes